language: python

services: docker

before_install:
  - docker -v
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t thrawny/docker-pipeline-demo-app2 ./web

script:
  - docker run thrawny/docker-pipeline-demo-app2 pytest

deploy:
  skip_cleanup: false
  provider: script
  script: docker push thrawny/docker-pipeline-demo-app2
  on:
    branch: master